from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from typing import Any


def export_csv(run: dict[str, Any], target_dir: str | Path) -> tuple[Path, Path]:
    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)
    nodes_path = target / "nodes.csv"
    edges_path = target / "edges.csv"
    with nodes_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["id", "label", "type"])
        writer.writeheader()
        for entity in run.get("entities", []):
            writer.writerow({key: entity.get(key) for key in writer.fieldnames})
    with edges_path.open("w", encoding="utf-8", newline="") as handle:
        fields = [
            "source_id",
            "relation",
            "target_id",
            "status",
            "probability",
            "confidence",
            "document_id",
            "evidence_start",
            "evidence_end",
            "evidence_text",
            "evidence_source_spans",
            "source_sha256",
            "canonical_sha256",
            "model",
        ]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for edge in run.get("edges", []):
            candidate = edge.get("candidate", {})
            decision = edge.get("decision", {})
            document = run.get("document", {})
            if edge.get("status") != "proposed":
                continue
            writer.writerow(
                {
                    "source_id": candidate.get("source_id"),
                    "relation": decision.get("selected"),
                    "target_id": candidate.get("target_id"),
                    "status": edge.get("status"),
                    "probability": decision.get("selected_probability"),
                    "confidence": decision.get("confidence"),
                    "document_id": candidate.get("document_id"),
                    "evidence_start": candidate.get("evidence_start"),
                    "evidence_end": candidate.get("evidence_end"),
                    "evidence_text": candidate.get("evidence_text"),
                    "evidence_source_spans": json.dumps(
                        candidate.get("evidence_source_spans", []),
                        sort_keys=True,
                        separators=(",", ":"),
                    ),
                    "source_sha256": document.get("source_sha256"),
                    "canonical_sha256": document.get("canonical_sha256"),
                    "model": decision.get("model"),
                }
            )
    return nodes_path, edges_path


def export_neo4j(run: dict[str, Any], path: str | Path) -> Path:
    destination = Path(path)
    document = run.get("document", {})
    lines = ["// Generated by JevGraph. Only proposed edges are included."]
    for entity in run.get("entities", []):
        lines.append(
            "MERGE (n:Entity {id: "
            + _literal(str(entity.get("id", "")))
            + "}) SET n.label = "
            + _literal(str(entity.get("label", "")))
            + ", n.entity_type = "
            + _literal(str(entity.get("type", "")))
            + ";"
        )
    for edge in run.get("edges", []):
        if edge.get("status") != "proposed":
            continue
        candidate = edge.get("candidate", {})
        decision = edge.get("decision", {})
        relation = _identifier(str(decision.get("selected", "relation")))
        lines.append(
            "MATCH (s:Entity {id: "
            + _literal(str(candidate.get("source_id", "")))
            + "}), (t:Entity {id: "
            + _literal(str(candidate.get("target_id", "")))
            + f"}}) MERGE (s)-[r:{relation}]->(t) "
            + "SET r.probability = "
            + str(float(decision.get("selected_probability", 0.0)))
            + ", r.confidence = "
            + str(float(decision.get("confidence", 0.0)))
            + ", r.document_id = "
            + _literal(str(candidate.get("document_id", "")))
            + ", r.evidence_text = "
            + _literal(str(candidate.get("evidence_text", "")))
            + ", r.evidence_start = "
            + str(int(candidate.get("evidence_start", 0)))
            + ", r.evidence_end = "
            + str(int(candidate.get("evidence_end", 0)))
            + ", r.evidence_source_spans = "
            + _literal(
                json.dumps(
                    candidate.get("evidence_source_spans", []),
                    sort_keys=True,
                    separators=(",", ":"),
                )
            )
            + ", r.source_sha256 = "
            + _literal(str(document.get("source_sha256") or ""))
            + ", r.canonical_sha256 = "
            + _literal(str(document.get("canonical_sha256") or ""))
            + ";"
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def _identifier(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not normalized or normalized[0].isdigit():
        normalized = "relation_" + normalized
    return normalized.upper()


def _literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
